### ISSUE TITLE
Building from sources

### ISSUE THREAD

**Issue by fatbulat** [hyst329/OpenFool#3]
How to build form the sources on linux? I've not seen `Makefile` or something like that.

By the way, when I see project of this kind I expect to see certain 'file system'. E.g. like this:
```
[dir] src
[file] README.md
[file] LICENSE
[file] Makefile
```

**Comment by hyst329** [comment]
@fatbulat The build process is managed by `qmake`, and the actual `Makefile` is _generated_ by the build system (because it's OS and compiler dependent). So, there is no need for `Makefile`. 
(I don't close this issue until adding "How to build" section to `README.md`).

**Comment by hyst329** [comment]
Now it's fixed. Instructions are added to `README.md`.
