### ISSUE TITLE
Passing

### ISSUE THREAD

**Issue by hyst329** [hyst329/OpenFool#30]
Allow to pass the attack to the left-side neighbour when no cards have been beaten, by adding a card of same value than the attacking card(s).

**Comment by czarkoff** [comment]
With an option in settings - some dislike this rule...

**Comment by hyst329** [comment]
@czarkoff Of course, it will be an option which can be disabled in settings.

**Comment by hyst329** [comment]
@czarkoff It's added in 0.2.8
