### ISSUE TITLE
Game logic in individual game

### ISSUE THREAD

**Issue by ildar** [hyst329/OpenFool#34]
is sometimes wrong

**Comment by hyst329** [comment]
@ildar What exactly is broken? I'll try to reproduce and fix it.

**Comment by ildar** [comment]
прошу прощения за задержку.
Игра с телефоном.
![screenshot_20180901-223656](https://user-images.githubusercontent.com/517752/45216076-2b519800-b2c1-11e8-9e12-ec2fbb3f9fab.png)

**Comment by hyst329** [comment]
@ildar sorry too, is it really individual or team game?
прошу прощения тоже, это точно каждый сам за себя или пара на пару?

**Comment by ildar** [comment]
стопудово один играл на телефоне :-)

**Comment by hyst329** [comment]
@ildar там опция есть, либо каждый из ботов играет сам за себя, либо пара на пару (игрок с ботом напротив)

**Comment by ildar** [comment]
ааа! ё! по умолчанию
Сейчас залез и увидел, что выбать не могу, ибо см. скриншот

**Comment by hyst329** [comment]
Исправлено в 0.2.7. Fixed in 0.2.7

**Comment by ildar** [comment]
не хочу открывать новый кейс.

v 0.2.7. из этого экрана нет выхода. Игра не заканчивается. Кнопка Back не
работает (хорошо бы, чтобы работала в любом случае)
