### ISSUE TITLE
Build on Linux

### ISSUE THREAD

**Issue by fatbulat** [hyst329/OpenFool#7]
I have a trouble with building on Linux. I run `qmake ../OpenFool.pro` (not just `OpenFool`). After I try to execute `make release`, but Make say target is not fund. Okay, I run `make` and it start to compile, but I receive error message again.

```lang=c++
../table.h:17:5: warning: identifier ‘nullptr’ is a keyword in C++11 [-Wc++0x-compat]
     Table(QObject *parent = nullptr);
     ^
```

What am I doing wrong?

**Comment by hyst329** [comment]
@fatbulat I'll try to reproduce this.

**Comment by hyst329** [comment]
Reproduced and fixed. The problem was that GCC on Windows includes C++11 headers by default and enables C++11 standard, which is not the case on Linux. Now it's properly fixed - but it's still necessary to run just `make`.
